<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ADM0027_Insert new portfolio</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>871e13b8-4d89-4b00-a1ef-81397491676d</testSuiteGuid>
   <testCaseLink>
      <guid>c6908e49-8a2c-4240-9a7f-9e742c0563a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ADM(Administation)/ADM0027_Insert New Portfolio</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7ae3c054-83ed-44bf-83d8-0a31a626cd37</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ADM data files/ADM0027_Insert new Portfolio (1)</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b143d657-2b3d-4161-97e2-d3aae7e775b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d0bdd3f-c8de-4613-a905-4509c24ebc4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7ae3c054-83ed-44bf-83d8-0a31a626cd37</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NewPortfolio</value>
         <variableId>b891d610-e4c2-49b0-bfb2-9fa2e7bf229e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7ae3c054-83ed-44bf-83d8-0a31a626cd37</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Description</value>
         <variableId>fa6e9179-9ff9-4844-b366-35382fbe6147</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
