<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ADM0032_Add data type</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ca71f8cd-0d52-434b-bee2-a72fa252c8e2</testSuiteGuid>
   <testCaseLink>
      <guid>fbc5500d-b7f5-454f-ae95-b0e13fa1a81d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ADM(Administation)/ADM0032_Add Data Type</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9a4ab455-6fa3-480c-9073-b44a88fc8983</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ADM data files/ADM0032_add data type (1)</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29be2af8-7b34-43bd-8227-96d614c8b390</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1330a0d0-ea43-4d90-8133-cdfa80af8fdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9a4ab455-6fa3-480c-9073-b44a88fc8983</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DatatypeName</value>
         <variableId>26ec430a-f1e1-47f9-9b5b-ff9be98d3e63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9a4ab455-6fa3-480c-9073-b44a88fc8983</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Description</value>
         <variableId>b0b8e665-1fe5-4cd9-84f6-cd07f045f115</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9a4ab455-6fa3-480c-9073-b44a88fc8983</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>BaseDataType</value>
         <variableId>961c708c-bd09-4a0a-a825-0e1172f8225d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
